FROM kong:latest

# Copy kong.yml to the container
COPY kong.yml /usr/local/kong/declarative/kong.yml

# Set environment variables
ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
ENV KONG_PROXY_ACCESS_LOG=/dev/stdout
ENV KONG_ADMIN_ACCESS_LOG=/dev/stdout
ENV KONG_PROXY_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_LISTEN=0.0.0.0:8000

# Expose necessary ports
EXPOSE 8000

# Start Kong using the declarative configuration
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["kong", "docker-start"]
